### ISSUE TITLE
 BucketName must not be null

### ISSUE THREAD

**Issue by nguyendai2193** [DeweyReed/UltimateMusicPicker#21] opened 2020-08-03 10:34 UTC
Error when i picker ringtone from phone:

E/UncaughtException: java.lang.IllegalStateException: bucketName must not be null
        at xyz.aprildown.ultimateringtonepicker.data.folder.RingtoneFolderRetrieverQ.getRingtoneFolders(RingtoneFolderRetrieverQ.kt:46)
        at xyz.aprildown.ultimateringtonepicker.data.folder.RingtoneFolderRetrieverCompat.getRingtoneFolders(Unknown Source:2)
        at xyz.aprildown.ultimateringtonepicker.data.DeviceRingtoneModel.getFolders(DeviceRingtoneModel.kt:116)
        at xyz.aprildown.ultimateringtonepicker.data.DeviceRingtoneModel.getCategories(DeviceRingtoneModel.kt:128)
        at xyz.aprildown.ultimateringtonepicker.RingtonePickerViewModel$categories$2$$special$$inlined$also$lambda$1.invokeSuspend(RingtonePickerViewModel.kt:76)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)

Here my code:
private fun createStandardSettings(uri: Uri): UltimateRingtonePicker.Settings =
            UltimateRingtonePicker.Settings(
                    preSelectUris = listOf(uri),
                    systemRingtonePicker = UltimateRingtonePicker.SystemRingtonePicker(
                            customSection = UltimateRingtonePicker.SystemRingtonePicker.CustomSection(),
                            defaultSection = UltimateRingtonePicker.SystemRingtonePicker.DefaultSection(
                                    showSilent = true
                            ),
                            ringtoneTypes = listOf(
                                    RingtoneManager.TYPE_RINGTONE
                            )
                    ),
                    deviceRingtonePicker = UltimateRingtonePicker.DeviceRingtonePicker(
                            deviceRingtoneTypes = listOf(
                                    UltimateRingtonePicker.RingtoneCategoryType.All,
                                    UltimateRingtonePicker.RingtoneCategoryType.Artist,
                                    UltimateRingtonePicker.RingtoneCategoryType.Album,
                                    UltimateRingtonePicker.RingtoneCategoryType.Folder
                            )
                    )
            )
 Please help me! Thanks.

**Comment by DeweyReed** [comment] 2020-08-04 02:43
The problem is fixed in https://github.com/DeweyReed/UltimateRingtonePicker/commit/91607018bb213cc26926593159fc5ead005e26df. You can upgrade to `3.0.0-beta01`. Currently, I choose to ignore folders without a bucket name.

**Closed as completed by DeweyReed** 2020-08-04 02:43 UTC
